### ISSUE TITLE
Design: initial ideas

### ISSUE THREAD

**Issue by tbtommyb** [CYPIAPT-LNDSE/friendly-friends#6]
Hi @princessrachel1 , we've been doing some thinking about how to make the app work best.

What we are thinking of is having a cat that you can stroke and talk to. It will ask you questions and you can choose a response. We are thinking that it would be a nice way for children to express how they feel without having to actually say that they feel depressed or anxious.

If you say that you feel sad it will give you a different message than if you said you feel happy so you can have different sections dealing with different mental issues.

We are thinking that it would be cool if the cat purred when you stroked it and talked to you about how it felt. We thought it would help kids feel more comfortable using the app.

The picture below is a really simple example of how it might work. Don't worry if you don't like exactly how it looks because we can change everything.

**What do you think of our idea to make the cat like a pet?**

<img width="319" alt="screen shot 2017-01-30 at 17 01 19" src="https://cloud.githubusercontent.com/assets/10003633/22433241/a12caddc-e70f-11e6-9e67-21eff5173eb5.png">

**Comment by princessrachel1** [comment]
i like it looks good

**Comment by princessrachel1** [comment]
yes it does
