### ISSUE TITLE
create an SVG cat

### ISSUE THREAD

**Issue by Jwhiles** [CYPIAPT-LNDSE/friendly-friends#9]

**Comment by iteles** [comment]
I mean, I don't know *exactly* what you're looking for here because there is no description in the issue, but @nogainbar created some beautiful SVG animals for Anna Freud before! Might help to avoid duplication of effort 👍

**Comment by tbtommyb** [comment]
In the end we decided that making the cat into an SVG with animations etc would be part of the roadmap rather than prototype.
